import React from 'react'
import Head from 'next/head'

const About = () => {
  return (
    <div>
      <Head>
        <title>Hunting Coder | About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mx-auto w-1/2 mt-10">
        <div className="w-full text-xl md:text-2xl lg:text-4xl font-semibold text-slate-800 text-center mb-10">
          Welcome to Hunter Coder
        </div>
        <div className="text-left text-xl ">
          <p className='leading-8'>
            Hello guys,<br/>
            This side Mohammad Asad Khan and I'm the developer of this side HunterCoder.com this is my very first website using latest and Popular React framework <b>Next.js</b>. <br/>
            This is an Blog website and also have a backend which is my own API..yes you're right you can submit your contact form also. This website do not use any sort of DB because it's just practise website therefore we are storing our user files and blog data on server only using Node module known as <b>"fileSystem"</b>
            This site uses SSG functionality that is (<b>Static Site Generation</b>) I have use this rendring method because my website data is not changing that fast therefore I choose this method over SSR (<b>Server Side Rendring</b>)
            <br/>
            I hope you guy's like this website and if you guys have any query then use contact form to contact me.
            <br/>
            Thank you and I will see you next time....❤<br/>
            <span className='text-xs'>10-August-2022 | 07 : 12 AM</span>
          </p>
        </div>
      </div>
    </div>
  )
}

export default About