import React from 'react'
import Head from 'next/head'
const Contact = () => {
  return (
    <div>
      <Head>
        <title>Hunting Coder | Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="text-3xl w-1/3 mx-auto font-semibold mt-10">
        Give us your response
      </div>
      <div className='w-1/2 mx-auto flex flex-row justify-center align-middle mt-12'>
        <form className="w-50 max-w-lg " action='http://localhost:3000/api/postContact' method='post'>
          <div className="flex flex-wrap -mx-3 mb-6">
            <div className="w-full md:w-1/2 px-3 mb-6 md:mb-0">
              <label className="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" htmlFor="name">
                Name
              </label>
              <input className="appearance-none block w-full bg-gray-200 text-gray-700  rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white" id="grid-first-name" name='name' type="text" placeholder="Jane" />
            </div>
            <div className="w-full md:w-1/2 px-3">
              <label className="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" htmlFor="email">
                email
              </label>
              <input className="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" id="email" name='email' type="email" placeholder="Doe0014@gmail.com" />
            </div>
          </div>
          <div className="flex flex-wrap -mx-3 mb-6">
            <div className="w-full px-3">
              <label className="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" htmlFor="comment">
                comment
              </label>
              <textarea className="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-gray-300 focus:border-gray-500 resize-none" rows="4" id="grid-password" placeholder="This site is need a lot of work" name='comment'/>
            </div>
          </div>
          <div className="flex flex-wrap -mx-3 mb-2">
            <div className="w-full px-3 mb-6 md:mb-0">
              <label className="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" htmlFor="mobile">
                Mobile NO.
              </label>
              <input className="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500 " id="grid-mobile" name="mobile" type="text" placeholder="99xxx457xxx" />
            </div>
          </div>
          <div>
            <button className="px-6 py-2 text-md bg-slate-500 mt-8 rounded hover:bg-slate-400 hover:cursor-pointer transition-colors delay-150 ease-in">Submit</button>
          </div>
        </form>
      </div>
    </div>
  )
}

export default Contact