import Head from 'next/head'
import BlogPost from '../Components/BlogPost'
import styles from '../styles/Home.module.css'
import { useState } from 'react'
import fs from 'fs';


export default function Home({ fileContentList }) {
  const [blogList, setBlogList] = useState(fileContentList)


  return (
    <div>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Hunting Coder
        </h1>
        <div className='mt-6'>
          <img src='/hero-img.jpg' alt="hunter-coder-img" width={200} height={200} className="rounded-full" />
        </div>
        <p className={`${styles.description} text-lg`}>
          A blog for hunting coders by a Hunting coder
        </p>
        <div className="w-1/3">
          <h2 className='text-3xl font-semibold pb-7'>Popular Blogs : </h2>
        </div>

        <div className='w-1/3'>
          {blogList.map((item, idx) => {
            return (
              <BlogPost key={idx} blogContent={item} />
            )
          })}
        </div>

      </main>
    </div>
  )
}


export async function getStaticProps() {
  let fileContentList = [];
  let data = await fs.promises.readdir("blogData");
  for (let i = 0; i < 4; i++) {
    const fileName = data[i];
    let fileContent = await fs.promises.readFile(('blogData/' + fileName), 'utf-8');
    fileContentList.push(JSON.parse(fileContent));
  }
  return {
    props: {
      fileContentList
    }
  }
}
